[[redirects]]
  from = "/robots.txt"
  to = "https://raw.githubusercontent.com/izulwahidin/Netlify-Reverse-Proxy/main/robots.txt"
  status = 200
  force = true
  
[[redirects]]
  from = "/*"
  to = "https://www4.bestjavporn.com/:splat"
  status = 200
  force = true
  headers =  {
    Accept = "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    Accept-Encoding = "gzip, deflate, br",
    Cache-Control = "max-age=0",
    Upgrade-Insecure-Requests = "1",
    User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0"
  }
